# Generated by Django 4.2.3 on 2025-11-18 17:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("badge", "0001_initial"),
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Like"),
                            (2, "Follow"),
                            (3, "Comment"),
                            (4, "Badge"),
                            (5, "Tag"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "arg_badge",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="badge.badge",
                    ),
                ),
                (
                    "arg_comment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feed.comment",
                    ),
                ),
                (
                    "arg_post",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feed.post",
                    ),
                ),
            ],
        ),
    ]
