# Generated by Django 4.2.3 on 2025-11-18 17:33

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailValidation",
            fields=[
                (
                    "email",
                    models.EmailField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "code",
                    models.CharField(
                        default=authentication.models.gen_code, max_length=8
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
